server:
  port: 9001
spring:
  application:
    name: service-verification-code
#  redis:
#    host: 127.0.0.1
#    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1