
server:
  port: 9100

spring:
  application:
    name: online-taxi-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
#  instance:
#    hostname: localhost
#    instance-id: online-taxi-zuul
#zuul:
#  ribbon:
#    eager-load:
#      enabled: true
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000


