server:
  #\u670D\u52A1\u7AEF\u53E3
  port: 8021

spring:
  application:
    #\u5E94\u7528\u540D\u79F0
    name: service-sms
    #\u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E
  datasource:
    #\u914D\u7F6E\u5F53\u524D\u4F7F\u7528\u7684\u6570\u636E\u6E90\u7684\u64CD\u4F5C\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    #\u914D\u7F6EMySQL\u7684\u9A71\u52A8\u7A0B\u5E8F\u7C7B
    driver-class-name: com.mysql.cj.jdbc.Driver
    #\u6570\u636E\u5E93\u8FDE\u63A5\u5730\u5740
    url: jdbc:mysql://localhost:3306/online-taxi-three?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #\u6570\u636E\u5E93\u8FDE\u63A5\u7528\u6237\u540D
    username: root
    #\u6570\u636E\u5E93\u8FDE\u63A5\u5BC6\u7801
    password: 123456
    #\u8FDB\u884C\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u7684\u914D\u7F6E
    dbcp2:
      #\u521D\u59CB\u5316\u63D0\u4F9B\u7684\u8FDE\u63A5\u6570
      initial-size: 5
      #\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u7684\u6700\u5C0F\u7EF4\u6301\u8FDE\u63A5\u6570
      min-idle: 5
      #\u6700\u5927\u7684\u8FDE\u63A5\u6570
      max-total: 5
      #\u7B49\u5F85\u8FDE\u63A5\u83B7\u53D6\u7684\u6700\u5927\u8D85\u65F6\u65F6\u95F4
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

#mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
      #,http://localhost:7901/eureka/,http://localhost:7902/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
